id: I9CC41898
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T17:07:21+00:00'
last_modified: '2022-06-15T16:26:55.255782+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19471
  title: ཉམས་མགུར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '9818':
      image_group_id: I2827
      title: ''
      total_pages: 364
      order: 1
      base_file: 9818.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
